version: '3.3'
services:

  db:
    image: mysql
    restart: always
    container_name: kamtar-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kamtar
      MYSQL_USER: kamtar
      MYSQL_PASSWORD: kamtar
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: kamtar-adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kamtar-app
    image: kamtar-app:latest
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules/

volumes:
  mysql_data:
